print("WELCOME TO SIMPLIFIED CALCULATOR")
a=float(input("whats your first number?"))
b=float(input("whats your second number?"))
print("ADDITION ",a+b)
print("SUBTRACTION ",a-b)
print("MULTIPLICATION ",a*b)
print("DIVISION ",a/b)
